name: Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-20.04
            runtime: linux-x64
          - name: Windows
            os: windows-latest
            runtime: win-x64
          - name: MacOS
            os: macos-latest
            runtime: osx-x64

    env:
      proj: "NxEditor"
      launcher: "NxEditor.Launcher"

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish NX-Editor
        shell: bash
        run: |
          dotnet publish src/${{ env.proj }}/${{ env.proj }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o ${{ matrix.config.name }} \
          -p:Version=${{ github.event.release.tag_name }}

      - name: Archive Build Files
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ../${{ matrix.config.runtime }}.zip
          directory: ${{ matrix.config.name }}
          path: ./**
          
      - name: Upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: ${{ matrix.config.runtime }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish NX-Editor Launcher
        shell: bash
        run: |
          dotnet publish src/${{ env.launcher }}/${{ env.launcher }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o Setup/${{ matrix.config.name }} \
          -p:Version=${{ github.event.release.tag_name }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishReadyToRun=true

      - name: Archive Launcher Build Files
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ../../${{ matrix.config.name }}-Launcher.zip
          directory: Setup/${{ matrix.config.name }}
          path: ./**
          
      - name: Upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: ${{ matrix.config.name }}-Launcher.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
