name: Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-20.04
            ext: ""
            runtime: linux-x64
          - name: Windows
            os: windows-latest
            ext: .exe
            runtime: win-x64

    env:
      proj: "NxEditor"
      launcher: "NxEditor.Launcher"

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish NX-Editor Binary
        shell: bash
        run: |
          dotnet publish src/${{ env.proj }}/${{ env.proj }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o ${{ matrix.config.name }} \
          -p:Version=${{ github.event.release.tag_name }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishReadyToRun=true

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: nxe${{ matrix.config.ext }}
          path: ${{ matrix.config.name }}/${{ env.proj }}${{ matrix.config.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish NX-Editor Launcher
        shell: bash
        run: |
          dotnet publish src/${{ env.launcher }}/${{ env.launcher }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o ${{ matrix.config.name }} \
          -p:Version=${{ github.event.release.tag_name }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishReadyToRun=true

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: NX-Editor-Launcher${{ matrix.config.ext }}
          path: ${{ matrix.config.name }}/${{ env.launcher }}${{ matrix.config.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
